// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7AFyOxwl0x1C9DM9nK-r8hAYlw_2fg-A',
    appId: '1:143004847244:web:a562c7cfe4d5724b383fa9',
    messagingSenderId: '143004847244',
    projectId: 'localcluster-99139',
    authDomain: 'localcluster-99139.firebaseapp.com',
    storageBucket: 'localcluster-99139.appspot.com',
    measurementId: 'G-CGTDHMCZ3X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBN13oIWb6iwlWTcUHEZE5UasIYy-Modqg',
    appId: '1:143004847244:android:96d724b35d747936383fa9',
    messagingSenderId: '143004847244',
    projectId: 'localcluster-99139',
    storageBucket: 'localcluster-99139.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8ij1pAc2D1KW_3toT3rttUHdHqZeZhQU',
    appId: '1:143004847244:ios:0754e6a90849679d383fa9',
    messagingSenderId: '143004847244',
    projectId: 'localcluster-99139',
    storageBucket: 'localcluster-99139.appspot.com',
    iosBundleId: 'com.vamshikrishna.local.local',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8ij1pAc2D1KW_3toT3rttUHdHqZeZhQU',
    appId: '1:143004847244:ios:a770ccf025ade59a383fa9',
    messagingSenderId: '143004847244',
    projectId: 'localcluster-99139',
    storageBucket: 'localcluster-99139.appspot.com',
    iosBundleId: 'com.vamshikrishna.local.local.RunnerTests',
  );
}
